import { useEffect } from "react";
import type { AspectRatio } from "@/utils/aspectRatioUtils";
import { saveEditorPreferences } from "../editorPreferences";
import type { useExportSettings } from "../export/useExportSettings";
import type { useAppearanceState } from "../state/useAppearanceState";

type Input = {
	appearance: ReturnType<typeof useAppearanceState>;
	exportSettings: ReturnType<typeof useExportSettings>;
	aspectRatio: AspectRatio;
	whisperExecutablePath: string | null;
	whisperModelPath: string | null;
};

export function useEditorPreferencesPersistence({
	appearance,
	exportSettings,
	aspectRatio,
	whisperExecutablePath,
	whisperModelPath,
}: Input) {
	useEffect(() => {
		saveEditorPreferences({
			wallpaper: appearance.wallpaper,
			shadowIntensity: appearance.shadowIntensity,
			backgroundBlur: appearance.backgroundBlur,
			zoomMotionBlur: appearance.zoomMotionBlur,
			zoomMotionBlurTuning: appearance.zoomMotionBlurTuning,
			autoApplyFreshRecordingAutoZooms: appearance.autoApplyFreshRecordingAutoZooms,
			connectZooms: appearance.connectZooms,
			defaultZoomSoundId: appearance.defaultZoomSoundId,
			defaultZoomPanSoundId: appearance.defaultZoomPanSoundId,
			defaultZoomOutSoundId: appearance.defaultZoomOutSoundId,
			zoomInDurationMs: appearance.zoomInDurationMs,
			zoomInOverlapMs: appearance.zoomInOverlapMs,
			zoomOutDurationMs: appearance.zoomOutDurationMs,
			connectedZoomGapMs: appearance.connectedZoomGapMs,
			connectedZoomDurationMs: appearance.connectedZoomDurationMs,
			zoomInEasing: appearance.zoomInEasing,
			zoomOutEasing: appearance.zoomOutEasing,
			connectedZoomEasing: appearance.connectedZoomEasing,
			showCursor: appearance.showCursor,
			loopCursor: appearance.loopCursor,
			cursorStyle: appearance.cursorStyle,
			cursorSize: appearance.cursorSize,
			cursorSmoothing: appearance.cursorSmoothing,
			cursorSpringStiffnessMultiplier: appearance.cursorSpringStiffnessMultiplier,
			cursorSpringDampingMultiplier: appearance.cursorSpringDampingMultiplier,
			cursorSpringMassMultiplier: appearance.cursorSpringMassMultiplier,
			cameraSpringStiffnessMultiplier: appearance.cameraSpringStiffnessMultiplier,
			cameraSpringDampingMultiplier: appearance.cameraSpringDampingMultiplier,
			cameraSpringMassMultiplier: appearance.cameraSpringMassMultiplier,
			cursorMotionBlur: appearance.cursorMotionBlur,
			cursorTrailEnabled: appearance.cursorTrailEnabled,
			cursorTrailSize: appearance.cursorTrailSize,
			cursorTrailLength: appearance.cursorTrailLength,
			cursorTrailDurationMs: appearance.cursorTrailDurationMs,
			cursorTrailColor: appearance.cursorTrailColor,
			cursorClickEffect: appearance.cursorClickEffect,
			cursorClickEffectColor: appearance.cursorClickEffectColor,
			cursorClickEffectScale: appearance.cursorClickEffectScale,
			cursorClickEffectOpacity: appearance.cursorClickEffectOpacity,
			cursorClickEffectDurationMs: appearance.cursorClickEffectDurationMs,
			rightClickEffect: appearance.rightClickEffect,
			leftClickSound: appearance.leftClickSound,
			rightClickSound: appearance.rightClickSound,
			cursorClickBounce: appearance.cursorClickBounce,
			cursorClickBounceDuration: appearance.cursorClickBounceDuration,
			cursorSway: appearance.cursorSway,
			borderRadius: appearance.borderRadius,
			videoOutlineWidth: appearance.videoOutlineWidth,
			videoOutlineColor: appearance.videoOutlineColor,
			padding: appearance.padding,
			webcam: appearance.webcam,
			aspectRatio,
			exportEncodingMode: exportSettings.exportEncodingMode,
			exportBackendPreference: exportSettings.exportBackendPreference,
			exportPipelineModel: exportSettings.exportPipelineModel,
			exportQuality: exportSettings.exportQuality,
			mp4FrameRate: exportSettings.mp4FrameRate,
			exportFormat: exportSettings.exportFormat,
			gifFrameRate: exportSettings.gifFrameRate,
			gifLoop: exportSettings.gifLoop,
			gifSizePreset: exportSettings.gifSizePreset,
			whisperExecutablePath,
			whisperModelPath,
		});
	}, [
		appearance.wallpaper,
		appearance.shadowIntensity,
		appearance.backgroundBlur,
		appearance.zoomMotionBlur,
		appearance.zoomMotionBlurTuning,
		appearance.autoApplyFreshRecordingAutoZooms,
		appearance.connectZooms,
		appearance.defaultZoomSoundId,
		appearance.defaultZoomPanSoundId,
		appearance.defaultZoomOutSoundId,
		appearance.zoomInDurationMs,
		appearance.zoomInOverlapMs,
		appearance.zoomOutDurationMs,
		appearance.connectedZoomGapMs,
		appearance.connectedZoomDurationMs,
		appearance.zoomInEasing,
		appearance.zoomOutEasing,
		appearance.connectedZoomEasing,
		appearance.showCursor,
		appearance.loopCursor,
		appearance.cursorStyle,
		appearance.cursorSize,
		appearance.cursorSmoothing,
		appearance.cursorSpringStiffnessMultiplier,
		appearance.cursorSpringDampingMultiplier,
		appearance.cursorSpringMassMultiplier,
		appearance.cameraSpringStiffnessMultiplier,
		appearance.cameraSpringDampingMultiplier,
		appearance.cameraSpringMassMultiplier,
		appearance.cursorMotionBlur,
		appearance.cursorTrailEnabled,
		appearance.cursorTrailSize,
		appearance.cursorTrailLength,
		appearance.cursorTrailDurationMs,
		appearance.cursorTrailColor,
		appearance.cursorClickEffect,
		appearance.cursorClickEffectColor,
		appearance.cursorClickEffectScale,
		appearance.cursorClickEffectOpacity,
		appearance.cursorClickEffectDurationMs,
		appearance.rightClickEffect,
		appearance.leftClickSound,
		appearance.rightClickSound,
		appearance.cursorClickBounce,
		appearance.cursorClickBounceDuration,
		appearance.cursorSway,
		appearance.borderRadius,
		appearance.videoOutlineWidth,
		appearance.videoOutlineColor,
		appearance.padding,
		appearance.webcam,
		aspectRatio,
		exportSettings.exportEncodingMode,
		exportSettings.exportBackendPreference,
		exportSettings.exportPipelineModel,
		exportSettings.exportQuality,
		exportSettings.mp4FrameRate,
		exportSettings.exportFormat,
		exportSettings.gifFrameRate,
		exportSettings.gifLoop,
		exportSettings.gifSizePreset,
		whisperExecutablePath,
		whisperModelPath,
	]);
}
