import path from "node:path";

/** Sources generated by Videos imports have independent, lossless audio companions. */
export function isLibrarySequenceSource(file: string): boolean {
	return (
		path.basename(path.dirname(file)) === ".recordly-media" &&
		/^[0-9a-f-]{36}\.mp4$/.test(path.basename(file))
	);
}
